### ISSUE TITLE
[Feature Request] Consider improving FSR2 visibility via DLL files

### ISSUE THREAD

**Issue by SaltyBet** [GPUOpen-Effects/FidelityFX-FSR2#76]
@rys, for your _(and your team's)_ consideration.

[SteamDB ](https://steamdb.info/) provides a wealth of information regarding games on [Steam](https://store.steampowered.com/).

That information includes [what kind of tech](https://steamdb.info/tech/) each game uses.

Such information is extracted via [File Detection RuleSets](https://github.com/SteamDatabase/FileDetectionRuleSets); is not exact, but it's still useful to be able to visualize approximate technology adoption growth.

One example is [AMD GPU Services](https://steamdb.info/tech/SDK/AMD_GPU_Services/); the AGS DLL pattern is detected, all is good.

Another example is [NVIDIA DLSS](https://steamdb.info/tech/SDK/NVIDIA_DLSS/); they enforce usage of their DLLs, so, once again, all is good.

Then we get to [AMD FSR2](https://steamdb.info/tech/SDK/AMD_FSR2/), and the picture becomes muddy due to the fact that DLL usage is optional.

Based on the information provided, maybe AMD could have the FSR2 solution always generate the DLLs during the build process, and advise developers to at least ship the DLLs with their games; that would improve FSR2's visibility tremendously.

Anyways, thanks for your time.

**Comment by 0x-FADED** [comment]
Hi FSR 2 is open source so there's no such thing as improving visibility or enforcement of rules such as only make or implement it available as a dll. Because of it being open source everyone has access to the source code so anyone can build it as static lib or as a dll and implement it as they like. to do this one just has to change a compiler option and nothing more. competitors to FSR2 are not fully open source(only their API is) so for their case making a static lib is not possible as a result they have only one way to implement the technologies by linking the dlls but because of FSR2 being fully open source there are multiple ways to implement it so the decision on how FSR2 implement it lies on developers and their choices I don't think AMD can do anything in this regard now you may close the issue....X)

**Comment by SaltyBet** [comment]
Hi.

Yes, I'm aware of the Open Source nature of FSR2, etc.

Do note the following:

- I did not imply taking away choice/freedom from the developers regarding how they implement FSR2 in their games _(static vs dynamic)_; just a consideration to always include the DLLs in either case.
- I did not mention "enforce", merely "advise".

It would still be interesting to see if there are replies from AMD personnel, so I'd like to leave this feature request open, if you don't mind.

**Comment by 0x-FADED** [comment]
Hi FSR 2 is open source so there's no such thing as improving visibility or enforcement of rules such as only make or implement it available as a dll. Because of it being open source everyone has access to the source code so anyone can build it as static lib or as a dll and implement it as they like. to do this one just has to change a compiler option and nothing more. competitors to FSR2 are not fully open source(only their API is) so for their case making a static lib is not possible as a result they have only one way to implement the technologies by linking the dlls but because of FSR2 being fully open source there are multiple ways to implement it so the decision on how FSR2 implement it lies on developers and their choices I don't think AMD can do anything in this regard now you may close the issue....X)

**Comment by 0x-FADED** [comment]
Well no problem 👍

**Comment by SaltyBet** [comment]
So, based on this:

https://gpuopen.com/presentations/2023/AMD_FidelityFX_Super_Resolution_3-Overview_and_Integration.pdf

... page 47:

- It is strongly recommended to integrate FSR 3 _via the DLL method_
  - It allows better debugging from AMD if the need arises
  - It allows _better future compatibility_ with newer versions of the technology

... AMD is now clear on their stance.

I guess I can close this feature request.

Thanks, Team AMD.
